#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TicTacToe.Resource", IsApplication=true)]

namespace TicTacToe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int won_anim = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_cell = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_control = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int btnAndroidGame = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int btnClose = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int btnExit = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int btnMainScreen = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int btnNewGame = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int btnOk = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int btnUserGame = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int linearlayoutMain = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int mainContent = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int mainHeader = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int tablelayout = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int txtvwCount = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int txtvwMessage = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int txtvwTitle = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DialogWindow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainScreen = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050009
			public const int ApplicationName = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int ButtonAndroidGame = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ButtonExit = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int ButtonMainScreen = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ButtonNewGame = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int ButtonUserGame = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int DialogBtnNo = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int DialogBtnYes = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int MainScreenTitle = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int MainTitle = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int Result = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
